package com.bithumb.auth.common.response;

public enum ErrorCode {

	AUTH_ANNOTATION_REQUIRED("INTERCEPTOR NO ANNOTATION"),
	ID_NOT_EXIST("ID NOT EXIST"),
	ID_ALREADY_EXIST("ID ALREADY EXIST"),
	ID_NOT_MATCH("ID NOT MATCH"),
	PASSWORD_NOT_MATCH("Password Not Match"),
	NICKNAME_ALREADY_EXIST("NICKNAME ALREADY EXIST"),
	USER_INFO_NOT_MATCH("USER ID & PASSWORD NOT MATCH"),
	REFRESH_TOKEN_IS_NOT_VALID("REFRESH TOKEN IS NOT VALID"),
	TOKEN_INVALID_SIGN("TOKEN INVALID SIGN"),
	TOKEN_IS_EXPIRED("TOKEN IS EXPIRED"),
	TOKEN_IS_NOT_SUPPORTED("TOKEN IS NOT SUPPORTED"),
	TOKEN_IS_NOT_VALID("TOKEN IS NOT VALID"),
	ALREADY_LOGOUT("ALREADY LOGOUT USER");

	private final String message;

	ErrorCode(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}
}