package com.bithumb.auth.common.response;

public enum ErrorCode {

	AUTH_ANNOTATION_REQUIRED("INTERCEPTOR NO ANNOTATION"),
	ID_NOT_EXIST("ID NOT EXIST"),
	ID_ALREADY_EXIST("ID ALREADY EXIST"),
	ID_NOT_MATCH("ID NOT MATCH"),
	PASSWORD_NOT_MATCH("Password Not Match"),
	NICKNAME_ALREADY_EXIST("NICKNAME ALREADY EXIST"),
	USER_INFO_NOT_MATCH("TOKEN IS EXPIRED OR USER ID & PASSWORD NOT MATCH"),
	REFRESH_TOKEN_IS_NOT_VALID("REFRESH TOKEN IS NOT VALID"),
	TOKEN_INVALID_SIGN("TOKEN INVALID SIGN"),
	TOKEN_IS_EXPIRED("TOKEN IS EXPIRED"),
	TOKEN_IS_NOT_SUPPORTED("TOKEN IS NOT SUPPORTED"),
	TOKEN_IS_NOT_VALID("TOKEN IS NOT VALID"),
	ALREADY_LOGOUT("TOKEN IS NOT VALID / DO LOGIN"),
	LIKE_BOARD_ALREADY_EXIST("LIKE BOARD ALREADY EXIST"),
	LIKE_BOARD_NOT_EXIST("LIKE BOARD NOT EXIST"),
	LIKE_COMMENT_ALREADY_EXIST("LIKE COMMENT ALREADY EXIST"),
	LIKE_COMMENT_NOT_EXIST("LIKE COMMENT NOT EXIST")
	;

	private final String message;

	ErrorCode(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}
}